import { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import { Toaster } from 'react-hot-toast';
import Providers from '~/hooks';
import '~/styles/global.css';

export const metadata: Metadata = {
  title: 'Whatsapp',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Toaster position="bottom-center" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
